[package]
name = "rust-ga"
version = "0.1.0"
authors = ["myth <myth@overflow.no>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
rand = "0.8"
structopt = "0.3"
